name: JS Test Reporting

# read-write repo token
# access to secrets
on:
  workflow_run:
    workflows: ['JS-build']
    types:
      - completed
permissions:
  contents: read
  actions: read
  checks: write

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/test-reporter@v2
        with:
          artifact: test-results
          name: JS - Tests
          path: '**/test-junit-report.xml'
          reporter: jest-junit
          fail-on-error: false
